name: Deploy to Cloud Run

on:
  pull_request:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          workload_identity_provider: 'projects/70756149774/locations/global/workloadIdentityPools/github-actions/providers/github-repos'
          service_account: 'hshn-devsecops-service-account@hs-heilbronn-devsecops.iam.gserviceaccount.com'

      - name: Deploy to Cloud Run
        uses: google-github-actions/deploy-cloudrun@v1
        with:
          service: note-api-hs-heilbronn-devsecops-budd
          source: "."
          region: europe-west3
          env_vars: |
            BACKEND=memory
            GOOGLE_CLOUD_PROJECT=${{ secrets.GCP_PROJECT_ID }}
            OTEL_SERVICE_NAME=note-api
            OTEL_EXPORTER_OTLP_ENDPOINT=https://cloudtrace.googleapis.com
            OTEL_PYTHON_LOG_CORRELATION=true
            OTEL_TRACES_SAMPLER=always_on
            OTEL_EXPORTER_OTLP_PROTOCOL=http/protobuf
            OTEL_TRACES_EXPORTER=otlp
